apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-cache.fullname" . }}
  labels:
    {{- include "helm-cache.labels" . | nindent 4 }}
data:
  config.yaml: |
    chartmuseumUrl: {{ .Values.chartmuseum.url | quote }}
    chartmuseumUsername: {{ .Values.chartmuseum.username | quote }}
    chartmuseumPassword: {{ .Values.chartmuseum.password | quote }}