{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-cache.fullname" . }}
  labels:
    {{- include "helm-cache.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-cache.fullname" . }}
  labels:
    {{- include "helm-cache.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-cache.fullname" . }}
  labels:
    {{- include "helm-cache.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-cache.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm-cache.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
